// Generated by Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="YQCKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif





@class NSCoder;

SWIFT_CLASS("_TtC6YQCKit10QCListView")
@interface QCListView : UIView
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class UIColor;
@class UICollectionView;
@class UICollectionReusableView;
@class UICollectionViewLayout;
@class UICollectionViewCell;
@class UIScrollView;

SWIFT_CLASS("_TtC6YQCKit16QCCollectionView")
@interface QCCollectionView : QCListView <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
/// 配置列表背景色
/// \param bgColor 背景色
///
///
/// returns:
/// self
- (QCCollectionView * _Nonnull)backgroundColor:(UIColor * _Nonnull)bgColor SWIFT_WARN_UNUSED_RESULT;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionReusableView * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView viewForSupplementaryElementOfKind:(NSString * _Nonnull)kind atIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout referenceSizeForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout referenceSizeForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillEndDragging:(UIScrollView * _Nonnull)scrollView withVelocity:(CGPoint)velocity targetContentOffset:(CGPoint * _Nonnull)targetContentOffset;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
@end


SWIFT_CLASS("_TtC6YQCKit11QCEmptyView")
@interface QCEmptyView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6YQCKit12QCKVObserver")
@interface QCKVObserver : NSObject
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




enum QCRefreshStatus : NSInteger;

SWIFT_CLASS("_TtC6YQCKit15QCListViewModel")
@interface QCListViewModel : NSObject
@property (nonatomic) enum QCRefreshStatus refresh;
@property (nonatomic) NSInteger page;
@property (nonatomic, copy) NSArray * _Nonnull dataArray;
@property (nonatomic) BOOL defaultOpenSection;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull openFlagArr;
@property (nonatomic) NSInteger defaultOpenSectionMaxCount;
@property (nonatomic) BOOL isPagable;
@property (nonatomic, copy) NSString * _Nonnull pageKeyName;
@property (nonatomic) NSInteger startPageNo;
@property (nonatomic) NSInteger pageSize;
@property (nonatomic, copy) void (^ _Nullable finishLoadClosure)(void);
@property (nonatomic, copy) void (^ _Nullable hasDataClosure)(void);
@property (nonatomic, copy) void (^ _Nullable failLoadClosure)(void);
@property (nonatomic, copy) void (^ _Nullable noDataClosure)(void);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull params;
- (void)loadMainDataWithIsMore:(BOOL)isMore param:(NSDictionary<NSString *, id> * _Nonnull)param;
- (void)handlePagableDataWithArray:(NSArray * _Nonnull)array;
- (void)handleErrorData;
@end

@class UIFont;
@class UILongPressGestureRecognizer;
@class UITapGestureRecognizer;

SWIFT_CLASS("_TtC6YQCKit15QCPadddingLabel")
@interface QCPadddingLabel : UILabel
- (void)drawTextInRect:(CGRect)rect;
- (CGRect)textRectForBounds:(CGRect)bounds limitedToNumberOfLines:(NSInteger)numberOfLines SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)frame:(CGFloat)x :(CGFloat)y :(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)frame:(CGRect)frame SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)size:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)size:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)origin:(CGPoint)origin SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)origin:(CGFloat)x :(CGFloat)y SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)center:(CGPoint)center SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)center:(CGFloat)centerX :(CGFloat)centerY SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)superView:(UIView * _Nonnull)superView SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)isHidden:(BOOL)isHidden SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)isUserInteractionEnabled:(BOOL)isUserInteractionEnabled SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)tag:(NSInteger)tag SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)shadowOpacity:(float)shadowOpacity SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)masksToBounds:(BOOL)masksToBounds SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)clipsToBounds:(BOOL)clipsToBounds SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)shadowColor:(UIColor * _Nonnull)shadowColor SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)shadowOffsetHeight:(CGFloat)shadowOffsetHeight SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)shadowOffsetWidth:(CGFloat)shadowOffsetWidth SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)shadowOffset:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)shadowOffset:(CGSize)shadowOffset SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)borderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)borderWidth:(CGFloat)borderWidth SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)cornerRadius:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)cornerRadiusWithClip:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)backgroundColor:(UIColor * _Nonnull)bgColor SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)alpha:(CGFloat)alpha SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)translatesAutoresizingMaskIntoConstraints:(BOOL)translatesAutoresizingMaskIntoConstraints SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)tintColor:(UIColor * _Nonnull)tintColor SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)tintAdjustmentMode:(UIViewTintAdjustmentMode)tintAdjustmentMode SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)clearsContextBeforeDrawing:(BOOL)clearsContextBeforeDrawing SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)mask:(UIView * _Nullable)mask SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)isOpaque:(BOOL)isOpaque SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)badgeText:(NSString * _Nonnull)badgeText SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)badgeDotWidth:(CGFloat)badgeDotWidth SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)badgeBgColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)badgeTextColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)badgeFont:(UIFont * _Nonnull)badgeFont SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)badgeHMargin:(CGFloat)badgeHMargin SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)badgeAlignRight:(BOOL)badgeAlignRight SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)badgeTop:(CGFloat)badgeTop SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)badgePadding:(CGFloat)hPadding :(CGFloat)vPadding SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)badgeBorderWidth:(CGFloat)badgeBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)badgeBorderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)showAllNumber:(BOOL)showAllNumber SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)text:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)textColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)textAlignment:(NSTextAlignment)textAlignment SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)numberOfLines:(NSInteger)numberOfLines SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)font:(UIFont * _Nonnull)font SWIFT_WARN_UNUSED_RESULT;
- (QCPadddingLabel * _Nonnull)addLongPressAction:(void (^ _Nullable)(QCPadddingLabel * _Nonnull))action SWIFT_WARN_UNUSED_RESULT;
- (void)addLongPress:(void (^ _Nullable)(QCPadddingLabel * _Nonnull))action;
- (void)longPressActionWithLongPress:(UILongPressGestureRecognizer * _Nonnull)longPress;
- (QCPadddingLabel * _Nonnull)removeLongPressAction SWIFT_WARN_UNUSED_RESULT;
- (void)removeLongPress;
- (QCPadddingLabel * _Nonnull)addAction:(void (^ _Nullable)(QCPadddingLabel * _Nonnull))action SWIFT_WARN_UNUSED_RESULT;
- (void)addTap:(void (^ _Nullable)(QCPadddingLabel * _Nonnull))action;
- (void)tapActionWithTap:(UITapGestureRecognizer * _Nonnull)tap;
- (QCPadddingLabel * _Nonnull)removeAction SWIFT_WARN_UNUSED_RESULT;
- (void)removeTap;
- (QCPadddingLabel * _Nonnull)textInsets:(UIEdgeInsets)textInsets SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, QCRefreshStatus, closed) {
  QCRefreshStatusNone = 0,
  QCRefreshStatusBeingHeaderRefresh = 1,
  QCRefreshStatusEndHeaderRefresh = 2,
  QCRefreshStatusBeingFooterRefresh = 3,
  QCRefreshStatusEndFooterRefresh = 4,
  QCRefreshStatusNoMoreData = 5,
  QCRefreshStatusError = 6,
  QCRefreshStatusNoAction = 7,
};

@class UITableView;
@class UITableViewCell;
@class UITableViewRowAction;

SWIFT_CLASS("_TtC6YQCKit11QCTableView")
@interface QCTableView : QCListView <UITableViewDataSource, UITableViewDelegate>
- (QCTableView * _Nonnull)backgroundColor:(UIColor * _Nonnull)bgColor SWIFT_WARN_UNUSED_RESULT;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// 代理和数据源
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForFooterInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (BOOL)tableView:(UITableView * _Nonnull)tableView canEditRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView willBeginEditingRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (NSArray<UITableViewRowAction *> * _Nullable)tableView:(UITableView * _Nonnull)tableView editActionsForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didEndEditingRowAtIndexPath:(NSIndexPath * _Nullable)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillEndDragging:(UIScrollView * _Nonnull)scrollView withVelocity:(CGPoint)velocity targetContentOffset:(CGPoint * _Nonnull)targetContentOffset;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
@end

typedef SWIFT_ENUM(NSInteger, QCTextFieldType, closed) {
  QCTextFieldTypeMoney = 0,
  QCTextFieldTypeNumberMoney = 1,
  QCTextFieldTypePhone = 2,
  QCTextFieldTypeIdCard = 3,
  QCTextFieldTypeEmail = 4,
  QCTextFieldTypeNumber = 5,
  QCTextFieldTypeLetter = 6,
  QCTextFieldTypeLetterOrNumber = 7,
  QCTextFieldTypeChineseCharacters = 8,
  QCTextFieldTypeNone = 9,
};

@class UICollectionViewLayoutAttributes;

SWIFT_CLASS("_TtC6YQCKit17QCWaterFlowLayout")
@interface QCWaterFlowLayout : UICollectionViewFlowLayout
- (void)prepareLayout;
- (NSArray<UICollectionViewLayoutAttributes *> * _Nullable)layoutAttributesForElementsInRect:(CGRect)rect SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewLayoutAttributes * _Nullable)layoutAttributesForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) CGSize collectionViewContentSize;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end





@class UIResponder;

@interface UIApplication (SWIFT_EXTENSION(YQCKit))
@property (nonatomic, readonly, strong) UIResponder * _Nullable nextResponder;
@end




@interface UIButton (SWIFT_EXTENSION(YQCKit))
- (UIButton * _Nonnull)frame:(CGFloat)x :(CGFloat)y :(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)frame:(CGRect)frame SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)size:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)size:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)origin:(CGPoint)origin SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)origin:(CGFloat)x :(CGFloat)y SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)center:(CGPoint)center SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)center:(CGFloat)centerX :(CGFloat)centerY SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)superView:(UIView * _Nonnull)superView SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)isHidden:(BOOL)isHidden SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)isUserInteractionEnabled:(BOOL)isUserInteractionEnabled SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)tag:(NSInteger)tag SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)shadowOpacity:(float)shadowOpacity SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)masksToBounds:(BOOL)masksToBounds SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)clipsToBounds:(BOOL)clipsToBounds SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)shadowColor:(UIColor * _Nonnull)shadowColor SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)shadowOffsetHeight:(CGFloat)shadowOffsetHeight SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)shadowOffsetWidth:(CGFloat)shadowOffsetWidth SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)shadowOffset:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)shadowOffset:(CGSize)shadowOffset SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)borderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)borderWidth:(CGFloat)borderWidth SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)cornerRadius:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)cornerRadiusWithClip:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)backgroundColor:(UIColor * _Nonnull)bgColor SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)isEnabled:(BOOL)isEnabled SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)isSelected:(BOOL)isSelected SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)isHighlighted:(BOOL)isHighlighted SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)alpha:(CGFloat)alpha SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)translatesAutoresizingMaskIntoConstraints:(BOOL)translatesAutoresizingMaskIntoConstraints SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)tintColor:(UIColor * _Nonnull)tintColor SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)tintAdjustmentMode:(UIViewTintAdjustmentMode)tintAdjustmentMode SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)clearsContextBeforeDrawing:(BOOL)clearsContextBeforeDrawing SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)mask:(UIView * _Nullable)mask SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)isOpaque:(BOOL)isOpaque SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)badgeText:(NSString * _Nonnull)badgeText SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)badgeDotWidth:(CGFloat)badgeDotWidth SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)badgeBgColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)badgeTextColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)badgeFont:(UIFont * _Nonnull)badgeFont SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)badgeHMargin:(CGFloat)badgeHMargin SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)badgeAlignRight:(BOOL)badgeAlignRight SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)badgeTop:(CGFloat)badgeTop SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)badgePadding:(CGFloat)hPadding :(CGFloat)vPadding SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)badgeBorderWidth:(CGFloat)badgeBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)badgeBorderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIButton * _Nonnull)showAllNumber:(BOOL)showAllNumber SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) UIColor * _Nullable qc_selBgColor;
@property (nonatomic, strong) UIColor * _Nullable qc_disableBgColor;
@property (nonatomic, strong) UIColor * _Nullable qc_highLightBgColor;
@property (nonatomic, strong) UIColor * _Nullable qc_norBorderColor;
@property (nonatomic, strong) UIColor * _Nullable qc_selBorderColor;
@property (nonatomic, strong) UIColor * _Nullable qc_disableBorderColor;
@property (nonatomic, strong) UIColor * _Nullable qc_highLightBorderColor;
- (UIButton * _Nonnull)addAction:(void (^ _Nullable)(UIButton * _Nonnull))action SWIFT_WARN_UNUSED_RESULT;
- (void)addTap:(void (^ _Nullable)(UIButton * _Nonnull))action;
- (UIButton * _Nonnull)addActionWithControlEvent:(void (^ _Nullable)(UIButton * _Nonnull))action :(UIControlEvents)controlEvent SWIFT_WARN_UNUSED_RESULT;
- (void)removeActionWithControlEvent:(UIControlEvents)controlEvent;
- (void)addTapWithControlEvent:(void (^ _Nullable)(UIButton * _Nonnull))action :(UIControlEvents)controlEvent;
- (void)removeTapWithControlEvent:(UIControlEvents)controlEvent;
- (UIButton * _Nonnull)removeAction SWIFT_WARN_UNUSED_RESULT;
- (void)removeTap;
- (void)swizzle_dealloc;
@end




@interface UICollectionView (SWIFT_EXTENSION(YQCKit))
- (UICollectionView * _Nonnull)frame:(CGFloat)x :(CGFloat)y :(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)frame:(CGRect)frame SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)size:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)size:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)origin:(CGPoint)origin SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)origin:(CGFloat)x :(CGFloat)y SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)center:(CGPoint)center SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)center:(CGFloat)centerX :(CGFloat)centerY SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)superView:(UIView * _Nonnull)superView SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)isHidden:(BOOL)isHidden SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)isUserInteractionEnabled:(BOOL)isUserInteractionEnabled SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)tag:(NSInteger)tag SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)shadowOpacity:(float)shadowOpacity SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)masksToBounds:(BOOL)masksToBounds SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)clipsToBounds:(BOOL)clipsToBounds SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)shadowColor:(UIColor * _Nonnull)shadowColor SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)shadowOffsetHeight:(CGFloat)shadowOffsetHeight SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)shadowOffsetWidth:(CGFloat)shadowOffsetWidth SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)shadowOffset:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)shadowOffset:(CGSize)shadowOffset SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)borderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)borderWidth:(CGFloat)borderWidth SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)cornerRadius:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)cornerRadiusWithClip:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)backgroundColor:(UIColor * _Nonnull)bgColor SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)contentSize:(CGSize)contentSize SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)bounces:(BOOL)bounces SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)isPagingEnabled:(BOOL)isPagingEnabled SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)showsVerticalScrollIndicator:(BOOL)showsVerticalScrollIndicator SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)showsHorizontalScrollIndicator:(BOOL)showsHorizontalScrollIndicator SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)isScrollEnabled:(BOOL)isScrollEnabled SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)alpha:(CGFloat)alpha SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)translatesAutoresizingMaskIntoConstraints:(BOOL)translatesAutoresizingMaskIntoConstraints SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)tintColor:(UIColor * _Nonnull)tintColor SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)tintAdjustmentMode:(UIViewTintAdjustmentMode)tintAdjustmentMode SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)clearsContextBeforeDrawing:(BOOL)clearsContextBeforeDrawing SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)mask:(UIView * _Nullable)mask SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)isOpaque:(BOOL)isOpaque SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)badgeText:(NSString * _Nonnull)badgeText SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)badgeDotWidth:(CGFloat)badgeDotWidth SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)badgeBgColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)badgeTextColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)badgeFont:(UIFont * _Nonnull)badgeFont SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)badgeHMargin:(CGFloat)badgeHMargin SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)badgeAlignRight:(BOOL)badgeAlignRight SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)badgeTop:(CGFloat)badgeTop SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)badgePadding:(CGFloat)hPadding :(CGFloat)vPadding SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)badgeBorderWidth:(CGFloat)badgeBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)badgeBorderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)showAllNumber:(BOOL)showAllNumber SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) void (^ _Nullable collectionViewAction)(UICollectionView * _Nonnull);
- (UICollectionView * _Nonnull)addAction:(void (^ _Nullable)(UICollectionView * _Nonnull))action SWIFT_WARN_UNUSED_RESULT;
- (void)addTap:(void (^ _Nullable)(UICollectionView * _Nonnull))action;
- (void)tapActionWithTap:(UITapGestureRecognizer * _Nonnull)tap;
- (UICollectionView * _Nonnull)removeAction SWIFT_WARN_UNUSED_RESULT;
- (void)removeTap;
@end




@interface UIControl (SWIFT_EXTENSION(YQCKit))
- (UIControl * _Nonnull)frame:(CGFloat)x :(CGFloat)y :(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)frame:(CGRect)frame SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)size:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)size:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)origin:(CGPoint)origin SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)origin:(CGFloat)x :(CGFloat)y SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)center:(CGPoint)center SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)center:(CGFloat)centerX :(CGFloat)centerY SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)superView:(UIView * _Nonnull)superView SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)isHidden:(BOOL)isHidden SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)isUserInteractionEnabled:(BOOL)isUserInteractionEnabled SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)tag:(NSInteger)tag SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)shadowOpacity:(float)shadowOpacity SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)masksToBounds:(BOOL)masksToBounds SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)clipsToBounds:(BOOL)clipsToBounds SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)shadowColor:(UIColor * _Nonnull)shadowColor SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)shadowOffsetHeight:(CGFloat)shadowOffsetHeight SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)shadowOffsetWidth:(CGFloat)shadowOffsetWidth SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)shadowOffset:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)shadowOffset:(CGSize)shadowOffset SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)borderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)borderWidth:(CGFloat)borderWidth SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)cornerRadius:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)cornerRadiusWithClip:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)backgroundColor:(UIColor * _Nonnull)bgColor SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)alpha:(CGFloat)alpha SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)tintColor:(UIColor * _Nonnull)tintColor SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)tintAdjustmentMode:(UIViewTintAdjustmentMode)tintAdjustmentMode SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)clearsContextBeforeDrawing:(BOOL)clearsContextBeforeDrawing SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)mask:(UIView * _Nullable)mask SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)isOpaque:(BOOL)isOpaque SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)translatesAutoresizingMaskIntoConstraints:(BOOL)translatesAutoresizingMaskIntoConstraints SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)badgeText:(NSString * _Nonnull)badgeText SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)badgeDotWidth:(CGFloat)badgeDotWidth SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)badgeBgColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)badgeTextColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)badgeFont:(UIFont * _Nonnull)badgeFont SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)badgeHMargin:(CGFloat)badgeHMargin SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)badgeAlignRight:(BOOL)badgeAlignRight SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)badgeTop:(CGFloat)badgeTop SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)badgePadding:(CGFloat)hPadding :(CGFloat)vPadding SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)badgeBorderWidth:(CGFloat)badgeBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)badgeBorderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)showAllNumber:(BOOL)showAllNumber SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) void (^ _Nullable controlAction)(UIControl * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable controlLongPressAction)(UIControl * _Nonnull);
- (UIControl * _Nonnull)addLongPressAction:(void (^ _Nullable)(UIControl * _Nonnull))action SWIFT_WARN_UNUSED_RESULT;
- (void)addLongPress:(void (^ _Nullable)(UIControl * _Nonnull))action;
- (void)longPressActionWithLongPress:(UILongPressGestureRecognizer * _Nonnull)longPress;
- (UIControl * _Nonnull)removeLongPressAction SWIFT_WARN_UNUSED_RESULT;
- (void)removeLongPress;
- (UIControl * _Nonnull)addAction:(void (^ _Nullable)(UIControl * _Nonnull))action SWIFT_WARN_UNUSED_RESULT;
- (void)addTap:(void (^ _Nullable)(UIControl * _Nonnull))action;
- (void)tapActionWithTap:(UITapGestureRecognizer * _Nonnull)tap;
- (UIControl * _Nonnull)removeAction SWIFT_WARN_UNUSED_RESULT;
- (void)removeTap;
- (UIControl * _Nonnull)isEnabled:(BOOL)isEnabled SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)isSelected:(BOOL)isSelected SWIFT_WARN_UNUSED_RESULT;
- (UIControl * _Nonnull)isHighlighted:(BOOL)isHighlighted SWIFT_WARN_UNUSED_RESULT;
@end




@interface UIImageView (SWIFT_EXTENSION(YQCKit))
- (UIImageView * _Nonnull)frame:(CGFloat)x :(CGFloat)y :(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)frame:(CGRect)frame SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)size:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)size:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)origin:(CGPoint)origin SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)origin:(CGFloat)x :(CGFloat)y SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)center:(CGPoint)center SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)center:(CGFloat)centerX :(CGFloat)centerY SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)superView:(UIView * _Nonnull)superView SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)isHidden:(BOOL)isHidden SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)isUserInteractionEnabled:(BOOL)isUserInteractionEnabled SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)tag:(NSInteger)tag SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)shadowOpacity:(float)shadowOpacity SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)masksToBounds:(BOOL)masksToBounds SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)clipsToBounds:(BOOL)clipsToBounds SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)shadowColor:(UIColor * _Nonnull)shadowColor SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)shadowOffsetHeight:(CGFloat)shadowOffsetHeight SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)shadowOffsetWidth:(CGFloat)shadowOffsetWidth SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)shadowOffset:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)shadowOffset:(CGSize)shadowOffset SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)borderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)borderWidth:(CGFloat)borderWidth SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)cornerRadius:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)cornerRadiusWithClip:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)backgroundColor:(UIColor * _Nonnull)bgColor SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)contentMode:(UIViewContentMode)contentMode SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)alpha:(CGFloat)alpha SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)translatesAutoresizingMaskIntoConstraints:(BOOL)translatesAutoresizingMaskIntoConstraints SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)tintColor:(UIColor * _Nonnull)tintColor SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)tintAdjustmentMode:(UIViewTintAdjustmentMode)tintAdjustmentMode SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)clearsContextBeforeDrawing:(BOOL)clearsContextBeforeDrawing SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)mask:(UIView * _Nullable)mask SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)isOpaque:(BOOL)isOpaque SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)badgeText:(NSString * _Nonnull)badgeText SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)badgeDotWidth:(CGFloat)badgeDotWidth SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)badgeBgColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)badgeTextColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)badgeFont:(UIFont * _Nonnull)badgeFont SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)badgeHMargin:(CGFloat)badgeHMargin SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)badgeAlignRight:(BOOL)badgeAlignRight SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)badgeTop:(CGFloat)badgeTop SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)badgePadding:(CGFloat)hPadding :(CGFloat)vPadding SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)badgeBorderWidth:(CGFloat)badgeBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)badgeBorderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIImageView * _Nonnull)showAllNumber:(BOOL)showAllNumber SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) void (^ _Nullable imageViewAction)(UIImageView * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable imageViewLongPressAction)(UIImageView * _Nonnull);
- (UIImageView * _Nonnull)addLongPressAction:(void (^ _Nullable)(UIImageView * _Nonnull))action SWIFT_WARN_UNUSED_RESULT;
- (void)addLongPress:(void (^ _Nullable)(UIImageView * _Nonnull))action;
- (void)longPressActionWithLongPress:(UILongPressGestureRecognizer * _Nonnull)longPress;
- (UIImageView * _Nonnull)removeLongPressAction SWIFT_WARN_UNUSED_RESULT;
- (void)removeLongPress;
- (UIImageView * _Nonnull)addAction:(void (^ _Nullable)(UIImageView * _Nonnull))action SWIFT_WARN_UNUSED_RESULT;
- (void)addTap:(void (^ _Nullable)(UIImageView * _Nonnull))action;
- (void)tapActionWithTap:(UITapGestureRecognizer * _Nonnull)tap;
- (UIImageView * _Nonnull)removeAction SWIFT_WARN_UNUSED_RESULT;
- (void)removeTap;
@end


@interface UILabel (SWIFT_EXTENSION(YQCKit))
- (UILabel * _Nonnull)frame:(CGFloat)x :(CGFloat)y :(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)frame:(CGRect)frame SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)size:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)size:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)origin:(CGPoint)origin SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)origin:(CGFloat)x :(CGFloat)y SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)center:(CGPoint)center SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)center:(CGFloat)centerX :(CGFloat)centerY SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)superView:(UIView * _Nonnull)superView SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)isHidden:(BOOL)isHidden SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)isUserInteractionEnabled:(BOOL)isUserInteractionEnabled SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)tag:(NSInteger)tag SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)shadowOpacity:(float)shadowOpacity SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)masksToBounds:(BOOL)masksToBounds SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)clipsToBounds:(BOOL)clipsToBounds SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)shadowColor:(UIColor * _Nonnull)shadowColor SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)shadowOffsetHeight:(CGFloat)shadowOffsetHeight SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)shadowOffsetWidth:(CGFloat)shadowOffsetWidth SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)shadowOffset:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)shadowOffset:(CGSize)shadowOffset SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)borderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)borderWidth:(CGFloat)borderWidth SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)cornerRadius:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)cornerRadiusWithClip:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)backgroundColor:(UIColor * _Nonnull)bgColor SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)alpha:(CGFloat)alpha SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)translatesAutoresizingMaskIntoConstraints:(BOOL)translatesAutoresizingMaskIntoConstraints SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)tintColor:(UIColor * _Nonnull)tintColor SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)tintAdjustmentMode:(UIViewTintAdjustmentMode)tintAdjustmentMode SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)clearsContextBeforeDrawing:(BOOL)clearsContextBeforeDrawing SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)mask:(UIView * _Nullable)mask SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)isOpaque:(BOOL)isOpaque SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)badgeText:(NSString * _Nonnull)badgeText SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)badgeDotWidth:(CGFloat)badgeDotWidth SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)badgeBgColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)badgeTextColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)badgeFont:(UIFont * _Nonnull)badgeFont SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)badgeHMargin:(CGFloat)badgeHMargin SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)badgeAlignRight:(BOOL)badgeAlignRight SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)badgeTop:(CGFloat)badgeTop SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)badgePadding:(CGFloat)hPadding :(CGFloat)vPadding SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)badgeBorderWidth:(CGFloat)badgeBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)badgeBorderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)showAllNumber:(BOOL)showAllNumber SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) void (^ _Nullable labelAction)(UILabel * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable labelLongPress)(UILabel * _Nonnull);
- (UILabel * _Nonnull)addLongPressAction:(void (^ _Nullable)(UILabel * _Nonnull))action SWIFT_WARN_UNUSED_RESULT;
- (void)addLongPress:(void (^ _Nullable)(UILabel * _Nonnull))action;
- (void)longPressActionWithLongPress:(UILongPressGestureRecognizer * _Nonnull)longPress;
- (UILabel * _Nonnull)removeLongPressAction SWIFT_WARN_UNUSED_RESULT;
- (void)removeLongPress;
- (UILabel * _Nonnull)addAction:(void (^ _Nullable)(UILabel * _Nonnull))action SWIFT_WARN_UNUSED_RESULT;
- (void)addTap:(void (^ _Nullable)(UILabel * _Nonnull))action;
- (void)tapActionWithTap:(UITapGestureRecognizer * _Nonnull)tap;
- (UILabel * _Nonnull)removeAction SWIFT_WARN_UNUSED_RESULT;
- (void)removeTap;
- (UILabel * _Nonnull)text:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)textColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)textAlignment:(NSTextAlignment)textAlignment SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)numberOfLines:(NSInteger)numberOfLines SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)font:(UIFont * _Nonnull)font SWIFT_WARN_UNUSED_RESULT;
- (UILabel * _Nonnull)textInsets:(UIEdgeInsets)textInsets SWIFT_WARN_UNUSED_RESULT;
@end


@interface UIProgressView (SWIFT_EXTENSION(YQCKit))
- (UIProgressView * _Nonnull)frame:(CGFloat)x :(CGFloat)y :(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)frame:(CGRect)frame SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)size:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)size:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)origin:(CGPoint)origin SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)origin:(CGFloat)x :(CGFloat)y SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)center:(CGPoint)center SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)center:(CGFloat)centerX :(CGFloat)centerY SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)superView:(UIView * _Nonnull)superView SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)isHidden:(BOOL)isHidden SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)isUserInteractionEnabled:(BOOL)isUserInteractionEnabled SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)tag:(NSInteger)tag SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)shadowOpacity:(float)shadowOpacity SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)masksToBounds:(BOOL)masksToBounds SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)clipsToBounds:(BOOL)clipsToBounds SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)cornerRadius:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)cornerRadiusWithClip:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)shadowColor:(UIColor * _Nonnull)shadowColor SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)shadowOffsetHeight:(CGFloat)shadowOffsetHeight SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)shadowOffsetWidth:(CGFloat)shadowOffsetWidth SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)shadowOffset:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)shadowOffset:(CGSize)shadowOffset SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)borderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)borderWidth:(CGFloat)borderWidth SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)backgroundColor:(UIColor * _Nonnull)bgColor SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)alpha:(CGFloat)alpha SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)badgeText:(NSString * _Nonnull)badgeText SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)badgeDotWidth:(CGFloat)badgeDotWidth SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)badgeBgColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)badgeTextColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)badgeFont:(UIFont * _Nonnull)badgeFont SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)badgeHMargin:(CGFloat)badgeHMargin SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)badgeAlignRight:(BOOL)badgeAlignRight SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)badgeTop:(CGFloat)badgeTop SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)badgePadding:(CGFloat)hPadding :(CGFloat)vPadding SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)badgeBorderWidth:(CGFloat)badgeBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)badgeBorderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)showAllNumber:(BOOL)showAllNumber SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)translatesAutoresizingMaskIntoConstraints:(BOOL)translatesAutoresizingMaskIntoConstraints SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)tintColor:(UIColor * _Nonnull)tintColor SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)tintAdjustmentMode:(UIViewTintAdjustmentMode)tintAdjustmentMode SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)clearsContextBeforeDrawing:(BOOL)clearsContextBeforeDrawing SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)mask:(UIView * _Nullable)mask SWIFT_WARN_UNUSED_RESULT;
- (UIProgressView * _Nonnull)isOpaque:(BOOL)isOpaque SWIFT_WARN_UNUSED_RESULT;
@end


@interface UIScrollView (SWIFT_EXTENSION(YQCKit))
- (UIScrollView * _Nonnull)frame:(CGFloat)x :(CGFloat)y :(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)frame:(CGRect)frame SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)size:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)size:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)origin:(CGPoint)origin SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)origin:(CGFloat)x :(CGFloat)y SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)center:(CGPoint)center SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)center:(CGFloat)centerX :(CGFloat)centerY SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)superView:(UIView * _Nonnull)superView SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)isHidden:(BOOL)isHidden SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)isUserInteractionEnabled:(BOOL)isUserInteractionEnabled SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)tag:(NSInteger)tag SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)shadowOpacity:(float)shadowOpacity SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)masksToBounds:(BOOL)masksToBounds SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)clipsToBounds:(BOOL)clipsToBounds SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)shadowColor:(UIColor * _Nonnull)shadowColor SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)shadowOffsetHeight:(CGFloat)shadowOffsetHeight SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)shadowOffsetWidth:(CGFloat)shadowOffsetWidth SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)shadowOffset:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)shadowOffset:(CGSize)shadowOffset SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)borderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)borderWidth:(CGFloat)borderWidth SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)cornerRadius:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)cornerRadiusWithClip:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)backgroundColor:(UIColor * _Nonnull)bgColor SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)alpha:(CGFloat)alpha SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)translatesAutoresizingMaskIntoConstraints:(BOOL)translatesAutoresizingMaskIntoConstraints SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)tintColor:(UIColor * _Nonnull)tintColor SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)tintAdjustmentMode:(UIViewTintAdjustmentMode)tintAdjustmentMode SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)clearsContextBeforeDrawing:(BOOL)clearsContextBeforeDrawing SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)mask:(UIView * _Nullable)mask SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)isOpaque:(BOOL)isOpaque SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)badgeBgColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)badgeTextColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)badgeFont:(UIFont * _Nonnull)badgeFont SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)badgeHMargin:(CGFloat)badgeHMargin SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)badgeAlignRight:(BOOL)badgeAlignRight SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)badgeTop:(CGFloat)badgeTop SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)badgePadding:(CGFloat)hPadding :(CGFloat)vPadding SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)badgeBorderWidth:(CGFloat)badgeBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)badgeBorderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)showAllNumber:(BOOL)showAllNumber SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) void (^ _Nullable scrollViewAction)(UIScrollView * _Nonnull);
- (UIScrollView * _Nonnull)addAction:(void (^ _Nullable)(UIScrollView * _Nonnull))action SWIFT_WARN_UNUSED_RESULT;
- (void)addTap:(void (^ _Nullable)(UIScrollView * _Nonnull))action;
- (void)tapActionWithTap:(UITapGestureRecognizer * _Nonnull)tap;
- (UIScrollView * _Nonnull)removeAction SWIFT_WARN_UNUSED_RESULT;
- (void)removeTap;
- (UIScrollView * _Nonnull)delegate:(id <UIScrollViewDelegate> _Nonnull)delegate SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)isScrollEnabled:(BOOL)isScrollEnabled SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)contentSize:(CGSize)contentSize SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)bounces:(BOOL)bounces SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)isPagingEnabled:(BOOL)isPagingEnabled SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)showsVerticalScrollIndicator:(BOOL)showsVerticalScrollIndicator SWIFT_WARN_UNUSED_RESULT;
- (UIScrollView * _Nonnull)showsHorizontalScrollIndicator:(BOOL)showsHorizontalScrollIndicator SWIFT_WARN_UNUSED_RESULT;
@end




@interface UISlider (SWIFT_EXTENSION(YQCKit))
- (UISlider * _Nonnull)frame:(CGFloat)x :(CGFloat)y :(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)frame:(CGRect)frame SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)size:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)size:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)origin:(CGPoint)origin SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)origin:(CGFloat)x :(CGFloat)y SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)center:(CGPoint)center SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)center:(CGFloat)centerX :(CGFloat)centerY SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)superView:(UIView * _Nonnull)superView SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)isHidden:(BOOL)isHidden SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)isUserInteractionEnabled:(BOOL)isUserInteractionEnabled SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)tag:(NSInteger)tag SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)shadowOpacity:(float)shadowOpacity SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)masksToBounds:(BOOL)masksToBounds SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)clipsToBounds:(BOOL)clipsToBounds SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)shadowColor:(UIColor * _Nonnull)shadowColor SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)shadowOffsetHeight:(CGFloat)shadowOffsetHeight SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)shadowOffsetWidth:(CGFloat)shadowOffsetWidth SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)shadowOffset:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)shadowOffset:(CGSize)shadowOffset SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)borderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)borderWidth:(CGFloat)borderWidth SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)cornerRadius:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)cornerRadiusWithClip:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)backgroundColor:(UIColor * _Nonnull)bgColor SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)alpha:(CGFloat)alpha SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)translatesAutoresizingMaskIntoConstraints:(BOOL)translatesAutoresizingMaskIntoConstraints SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)tintColor:(UIColor * _Nonnull)tintColor SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)tintAdjustmentMode:(UIViewTintAdjustmentMode)tintAdjustmentMode SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)clearsContextBeforeDrawing:(BOOL)clearsContextBeforeDrawing SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)mask:(UIView * _Nullable)mask SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)isOpaque:(BOOL)isOpaque SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)isEnabled:(BOOL)isEnabled SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)isSelected:(BOOL)isSelected SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)isHighlighted:(BOOL)isHighlighted SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)badgeText:(NSString * _Nonnull)badgeText SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)badgeDotWidth:(CGFloat)badgeDotWidth SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)badgeBgColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)badgeTextColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)badgeFont:(UIFont * _Nonnull)badgeFont SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)badgeHMargin:(CGFloat)badgeHMargin SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)badgeAlignRight:(BOOL)badgeAlignRight SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)badgeTop:(CGFloat)badgeTop SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)badgePadding:(CGFloat)hPadding :(CGFloat)vPadding SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)badgeBorderWidth:(CGFloat)badgeBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)badgeBorderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UISlider * _Nonnull)showAllNumber:(BOOL)showAllNumber SWIFT_WARN_UNUSED_RESULT;
- (void)swizzle_dealloc;
@end


@interface UISwitch (SWIFT_EXTENSION(YQCKit))
- (UISwitch * _Nonnull)frame:(CGFloat)x :(CGFloat)y :(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)frame:(CGRect)frame SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)size:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)size:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)origin:(CGPoint)origin SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)origin:(CGFloat)x :(CGFloat)y SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)center:(CGPoint)center SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)center:(CGFloat)centerX :(CGFloat)centerY SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)superView:(UIView * _Nonnull)superView SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)isHidden:(BOOL)isHidden SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)isUserInteractionEnabled:(BOOL)isUserInteractionEnabled SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)tag:(NSInteger)tag SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)shadowOpacity:(float)shadowOpacity SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)masksToBounds:(BOOL)masksToBounds SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)clipsToBounds:(BOOL)clipsToBounds SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)shadowColor:(UIColor * _Nonnull)shadowColor SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)shadowOffsetHeight:(CGFloat)shadowOffsetHeight SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)shadowOffsetWidth:(CGFloat)shadowOffsetWidth SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)shadowOffset:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)shadowOffset:(CGSize)shadowOffset SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)borderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)borderWidth:(CGFloat)borderWidth SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)cornerRadius:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)cornerRadiusWithClip:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)backgroundColor:(UIColor * _Nonnull)bgColor SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)alpha:(CGFloat)alpha SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)translatesAutoresizingMaskIntoConstraints:(BOOL)translatesAutoresizingMaskIntoConstraints SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)tintColor:(UIColor * _Nonnull)tintColor SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)tintAdjustmentMode:(UIViewTintAdjustmentMode)tintAdjustmentMode SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)clearsContextBeforeDrawing:(BOOL)clearsContextBeforeDrawing SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)mask:(UIView * _Nullable)mask SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)isOpaque:(BOOL)isOpaque SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)isEnabled:(BOOL)isEnabled SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)isSelected:(BOOL)isSelected SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)isHighlighted:(BOOL)isHighlighted SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)badgeText:(NSString * _Nonnull)badgeText SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)badgeDotWidth:(CGFloat)badgeDotWidth SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)badgeBgColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)badgeTextColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)badgeFont:(UIFont * _Nonnull)badgeFont SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)badgeHMargin:(CGFloat)badgeHMargin SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)badgeAlignRight:(BOOL)badgeAlignRight SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)badgeTop:(CGFloat)badgeTop SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)badgePadding:(CGFloat)hPadding :(CGFloat)vPadding SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)badgeBorderWidth:(CGFloat)badgeBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)badgeBorderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UISwitch * _Nonnull)showAllNumber:(BOOL)showAllNumber SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) void (^ _Nullable switchAction)(UISwitch * _Nonnull);
- (UISwitch * _Nonnull)addAction:(void (^ _Nullable)(UISwitch * _Nonnull))action SWIFT_WARN_UNUSED_RESULT;
- (void)addTap:(void (^ _Nullable)(UISwitch * _Nonnull))action;
- (void)switchDidChange;
@end




@interface UITableView (SWIFT_EXTENSION(YQCKit))
- (UITableView * _Nonnull)frame:(CGFloat)x :(CGFloat)y :(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)frame:(CGRect)frame SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)size:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)size:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)origin:(CGPoint)origin SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)origin:(CGFloat)x :(CGFloat)y SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)center:(CGPoint)center SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)center:(CGFloat)centerX :(CGFloat)centerY SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)superView:(UIView * _Nonnull)superView SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)isHidden:(BOOL)isHidden SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)isUserInteractionEnabled:(BOOL)isUserInteractionEnabled SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)tag:(NSInteger)tag SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)shadowOpacity:(float)shadowOpacity SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)masksToBounds:(BOOL)masksToBounds SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)clipsToBounds:(BOOL)clipsToBounds SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)shadowColor:(UIColor * _Nonnull)shadowColor SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)shadowOffsetHeight:(CGFloat)shadowOffsetHeight SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)shadowOffsetWidth:(CGFloat)shadowOffsetWidth SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)shadowOffset:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)shadowOffset:(CGSize)shadowOffset SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)borderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)borderWidth:(CGFloat)borderWidth SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)cornerRadius:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)cornerRadiusWithClip:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)backgroundColor:(UIColor * _Nonnull)bgColor SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)contentSize:(CGSize)contentSize SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)bounces:(BOOL)bounces SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)isPagingEnabled:(BOOL)isPagingEnabled SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)showsVerticalScrollIndicator:(BOOL)showsVerticalScrollIndicator SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)showsHorizontalScrollIndicator:(BOOL)showsHorizontalScrollIndicator SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)isScrollEnabled:(BOOL)isScrollEnabled SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)alpha:(CGFloat)alpha SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)translatesAutoresizingMaskIntoConstraints:(BOOL)translatesAutoresizingMaskIntoConstraints SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)tintColor:(UIColor * _Nonnull)tintColor SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)tintAdjustmentMode:(UIViewTintAdjustmentMode)tintAdjustmentMode SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)clearsContextBeforeDrawing:(BOOL)clearsContextBeforeDrawing SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)mask:(UIView * _Nullable)mask SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)isOpaque:(BOOL)isOpaque SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)badgeText:(NSString * _Nonnull)badgeText SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)badgeDotWidth:(CGFloat)badgeDotWidth SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)badgeBgColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)badgeTextColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)badgeFont:(UIFont * _Nonnull)badgeFont SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)badgeHMargin:(CGFloat)badgeHMargin SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)badgeAlignRight:(BOOL)badgeAlignRight SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)badgeTop:(CGFloat)badgeTop SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)badgePadding:(CGFloat)hPadding :(CGFloat)vPadding SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)badgeBorderWidth:(CGFloat)badgeBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)badgeBorderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UITableView * _Nonnull)showAllNumber:(BOOL)showAllNumber SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) void (^ _Nullable tableViewAction)(UITableView * _Nonnull);
- (UITableView * _Nonnull)addAction:(void (^ _Nullable)(UITableView * _Nonnull))action SWIFT_WARN_UNUSED_RESULT;
- (void)addTap:(void (^ _Nullable)(UITableView * _Nonnull))action;
- (void)tapActionWithTap:(UITapGestureRecognizer * _Nonnull)tap;
- (UITableView * _Nonnull)removeAction SWIFT_WARN_UNUSED_RESULT;
- (void)removeTap;
@end




@interface UITextField (SWIFT_EXTENSION(YQCKit))
- (UITextField * _Nonnull)frame:(CGFloat)x :(CGFloat)y :(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)frame:(CGRect)frame SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)size:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)size:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)origin:(CGPoint)origin SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)origin:(CGFloat)x :(CGFloat)y SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)center:(CGPoint)center SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)center:(CGFloat)centerX :(CGFloat)centerY SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)superView:(UIView * _Nonnull)superView SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)isHidden:(BOOL)isHidden SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)isUserInteractionEnabled:(BOOL)isUserInteractionEnabled SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)tag:(NSInteger)tag SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)shadowOpacity:(float)shadowOpacity SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)masksToBounds:(BOOL)masksToBounds SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)clipsToBounds:(BOOL)clipsToBounds SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)shadowColor:(UIColor * _Nonnull)shadowColor SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)shadowOffsetHeight:(CGFloat)shadowOffsetHeight SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)shadowOffsetWidth:(CGFloat)shadowOffsetWidth SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)shadowOffset:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)shadowOffset:(CGSize)shadowOffset SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)borderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)borderWidth:(CGFloat)borderWidth SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)cornerRadius:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)cornerRadiusWithClip:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)backgroundColor:(UIColor * _Nonnull)bgColor SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)isEnabled:(BOOL)isEnabled SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)isSelected:(BOOL)isSelected SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)isHighlighted:(BOOL)isHighlighted SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)alpha:(CGFloat)alpha SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)tintColor:(UIColor * _Nonnull)tintColor SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)tintAdjustmentMode:(UIViewTintAdjustmentMode)tintAdjustmentMode SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)clearsContextBeforeDrawing:(BOOL)clearsContextBeforeDrawing SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)mask:(UIView * _Nullable)mask SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)isOpaque:(BOOL)isOpaque SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)translatesAutoresizingMaskIntoConstraints:(BOOL)translatesAutoresizingMaskIntoConstraints SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)badgeText:(NSString * _Nonnull)badgeText SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)badgeDotWidth:(CGFloat)badgeDotWidth SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)badgeBgColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)badgeTextColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)badgeFont:(UIFont * _Nonnull)badgeFont SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)badgeHMargin:(CGFloat)badgeHMargin SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)badgeAlignRight:(BOOL)badgeAlignRight SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)badgeTop:(CGFloat)badgeTop SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)badgePadding:(CGFloat)hPadding :(CGFloat)vPadding SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)badgeBorderWidth:(CGFloat)badgeBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)badgeBorderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UITextField * _Nonnull)showAllNumber:(BOOL)showAllNumber SWIFT_WARN_UNUSED_RESULT;
- (void)rightTapAction;
- (UITextField * _Nonnull)removeRightViewAction SWIFT_WARN_UNUSED_RESULT;
- (void)removeRightViewTap;
@property (nonatomic, copy) void (^ _Nullable rightViewAction)(UIView * _Nonnull);
@property (nonatomic, strong) UIColor * _Nullable qc_placeholderColor;
- (UITextField * _Nonnull)addAction:(void (^ _Nullable)(UITextField * _Nonnull))action SWIFT_WARN_UNUSED_RESULT;
- (void)addTap:(void (^ _Nullable)(UITextField * _Nonnull))action;
- (UITextField * _Nonnull)removeAction SWIFT_WARN_UNUSED_RESULT;
- (void)removeTap;
- (void)swizzle_dealloc;
@end




@interface UITextView (SWIFT_EXTENSION(YQCKit))
- (UITextView * _Nonnull)frame:(CGFloat)x :(CGFloat)y :(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)frame:(CGRect)frame SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)size:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)size:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)origin:(CGPoint)origin SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)origin:(CGFloat)x :(CGFloat)y SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)center:(CGPoint)center SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)center:(CGFloat)centerX :(CGFloat)centerY SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)superView:(UIView * _Nonnull)superView SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)isHidden:(BOOL)isHidden SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)isUserInteractionEnabled:(BOOL)isUserInteractionEnabled SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)tag:(NSInteger)tag SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)shadowOpacity:(float)shadowOpacity SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)masksToBounds:(BOOL)masksToBounds SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)clipsToBounds:(BOOL)clipsToBounds SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)shadowColor:(UIColor * _Nonnull)shadowColor SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)shadowOffsetHeight:(CGFloat)shadowOffsetHeight SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)shadowOffsetWidth:(CGFloat)shadowOffsetWidth SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)shadowOffset:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)shadowOffset:(CGSize)shadowOffset SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)borderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)borderWidth:(CGFloat)borderWidth SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)cornerRadius:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)cornerRadiusWithClip:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)backgroundColor:(UIColor * _Nonnull)bgColor SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)showsHorizontalScrollIndicator:(BOOL)showsHorizontalScrollIndicator SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)showsVerticalScrollIndicator:(BOOL)showsVerticalScrollIndicator SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)isScrollEnabled:(BOOL)isScrollEnabled SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)alpha:(CGFloat)alpha SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)translatesAutoresizingMaskIntoConstraints:(BOOL)translatesAutoresizingMaskIntoConstraints SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)tintColor:(UIColor * _Nonnull)tintColor SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)tintAdjustmentMode:(UIViewTintAdjustmentMode)tintAdjustmentMode SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)clearsContextBeforeDrawing:(BOOL)clearsContextBeforeDrawing SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)mask:(UIView * _Nullable)mask SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)isOpaque:(BOOL)isOpaque SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)badgeText:(NSString * _Nonnull)badgeText SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)badgeDotWidth:(CGFloat)badgeDotWidth SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)badgeBgColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)badgeTextColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)badgeFont:(UIFont * _Nonnull)badgeFont SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)badgeHMargin:(CGFloat)badgeHMargin SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)badgeAlignRight:(BOOL)badgeAlignRight SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)badgeTop:(CGFloat)badgeTop SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)badgePadding:(CGFloat)hPadding :(CGFloat)vPadding SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)badgeBorderWidth:(CGFloat)badgeBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)badgeBorderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)showAllNumber:(BOOL)showAllNumber SWIFT_WARN_UNUSED_RESULT;
- (UITextView * _Nonnull)addAction:(void (^ _Nullable)(UITextView * _Nonnull))action SWIFT_WARN_UNUSED_RESULT;
- (void)addTap:(void (^ _Nullable)(UITextView * _Nonnull))action;
- (UITextView * _Nonnull)removeAction SWIFT_WARN_UNUSED_RESULT;
- (void)removeTap;
- (void)swizzle_dealloc;
@end


@interface UIToolbar (SWIFT_EXTENSION(YQCKit))
- (UIToolbar * _Nonnull)frame:(CGFloat)x :(CGFloat)y :(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)frame:(CGRect)frame SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)size:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)size:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)origin:(CGPoint)origin SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)origin:(CGFloat)x :(CGFloat)y SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)center:(CGPoint)center SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)center:(CGFloat)centerX :(CGFloat)centerY SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)superView:(UIView * _Nonnull)superView SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)isHidden:(BOOL)isHidden SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)isUserInteractionEnabled:(BOOL)isUserInteractionEnabled SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)tag:(NSInteger)tag SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)shadowOpacity:(float)shadowOpacity SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)masksToBounds:(BOOL)masksToBounds SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)clipsToBounds:(BOOL)clipsToBounds SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)shadowColor:(UIColor * _Nonnull)shadowColor SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)shadowOffsetHeight:(CGFloat)shadowOffsetHeight SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)shadowOffsetWidth:(CGFloat)shadowOffsetWidth SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)shadowOffset:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)shadowOffset:(CGSize)shadowOffset SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)borderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)borderWidth:(CGFloat)borderWidth SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)cornerRadius:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)cornerRadiusWithClip:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)backgroundColor:(UIColor * _Nonnull)bgColor SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)alpha:(CGFloat)alpha SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)translatesAutoresizingMaskIntoConstraints:(BOOL)translatesAutoresizingMaskIntoConstraints SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)tintColor:(UIColor * _Nonnull)tintColor SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)tintAdjustmentMode:(UIViewTintAdjustmentMode)tintAdjustmentMode SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)clearsContextBeforeDrawing:(BOOL)clearsContextBeforeDrawing SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)mask:(UIView * _Nullable)mask SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)isOpaque:(BOOL)isOpaque SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)badgeText:(NSString * _Nonnull)badgeText SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)badgeDotWidth:(CGFloat)badgeDotWidth SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)badgeBgColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)badgeTextColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)badgeFont:(UIFont * _Nonnull)badgeFont SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)badgeHMargin:(CGFloat)badgeHMargin SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)badgeAlignRight:(BOOL)badgeAlignRight SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)badgeTop:(CGFloat)badgeTop SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)badgePadding:(CGFloat)hPadding :(CGFloat)vPadding SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)badgeBorderWidth:(CGFloat)badgeBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)badgeBorderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIToolbar * _Nonnull)showAllNumber:(BOOL)showAllNumber SWIFT_WARN_UNUSED_RESULT;
@end




@interface UIView (SWIFT_EXTENSION(YQCKit))
- (UIView * _Nonnull)frame:(CGFloat)x :(CGFloat)y :(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)frame:(CGRect)frame SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)size:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)size:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)origin:(CGPoint)origin SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)origin:(CGFloat)x :(CGFloat)y SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)center:(CGPoint)center SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)center:(CGFloat)centerX :(CGFloat)centerY SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)superView:(UIView * _Nonnull)superView SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)isHidden:(BOOL)isHidden SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)isUserInteractionEnabled:(BOOL)isUserInteractionEnabled SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)tag:(NSInteger)tag SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)borderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)borderWidth:(CGFloat)borderWidth SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)cornerRadius:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)cornerRadiusWithClip:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)shadowOpacity:(float)shadowOpacity SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)masksToBounds:(BOOL)masksToBounds SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)clipsToBounds:(BOOL)clipsToBounds SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)shadowColor:(UIColor * _Nonnull)shadowColor SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)shadowOffsetHeight:(CGFloat)shadowOffsetHeight SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)shadowOffsetWidth:(CGFloat)shadowOffsetWidth SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)shadowOffset:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)shadowOffset:(CGSize)shadowOffset SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)backgroundColor:(UIColor * _Nonnull)bgColor SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)contentMode:(UIViewContentMode)contentMode SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)alpha:(CGFloat)alpha SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)tintColor:(UIColor * _Nonnull)tintColor SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)tintAdjustmentMode:(UIViewTintAdjustmentMode)tintAdjustmentMode SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)clearsContextBeforeDrawing:(BOOL)clearsContextBeforeDrawing SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)mask:(UIView * _Nullable)mask SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)isOpaque:(BOOL)isOpaque SWIFT_WARN_UNUSED_RESULT;
- (void)cornerRadiusWithClipNoChain:(CGFloat)cornerRadius;
- (UIView * _Nonnull)translatesAutoresizingMaskIntoConstraints:(BOOL)translatesAutoresizingMaskIntoConstraints SWIFT_WARN_UNUSED_RESULT;
- (void)showVisualEffectView:(UIView * _Nullable)blurContentView :(enum UIBlurEffectStyle)style :(CGFloat)blurAlpha;
- (void)hideVisualEffectView;
- (UIView * _Nonnull)badgeText:(NSString * _Nonnull)badgeText SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)badgeDotWidth:(CGFloat)badgeDotWidth SWIFT_WARN_UNUSED_RESULT;
- (void)badgeIsHidden:(BOOL)badgeIsHidden;
- (UIView * _Nonnull)badgeBgColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)badgeTextColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)badgeFont:(UIFont * _Nonnull)badgeFont SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)badgeHMargin:(CGFloat)badgeHMargin SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)badgeAlignRight:(BOOL)badgeAlignRight SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)badgeTop:(CGFloat)badgeTop SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)badgePadding:(CGFloat)hPadding :(CGFloat)vPadding SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)badgeBorderWidth:(CGFloat)badgeBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)badgeBorderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)showAllNumber:(BOOL)showAllNumber SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) void (^ _Nullable longPress)(UIView * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable action)(UIView * _Nonnull);
- (UIView * _Nonnull)addLongPressAction:(void (^ _Nullable)(UIView * _Nonnull))action SWIFT_WARN_UNUSED_RESULT;
- (void)addLongPress:(void (^ _Nullable)(UIView * _Nonnull))action;
- (UIView * _Nonnull)removeLongPressAction SWIFT_WARN_UNUSED_RESULT;
- (void)removeLongPress;
- (UIView * _Nonnull)addAction:(void (^ _Nullable)(UIView * _Nonnull))action SWIFT_WARN_UNUSED_RESULT;
- (void)longPressActionWithLongPress:(UILongPressGestureRecognizer * _Nonnull)longPress;
- (void)addTap:(void (^ _Nullable)(UIView * _Nonnull))action;
- (void)tapActionWithTap:(UITapGestureRecognizer * _Nonnull)tap;
- (UIView * _Nonnull)removeAction SWIFT_WARN_UNUSED_RESULT;
- (void)removeTap;
@end


@interface UIWebView (SWIFT_EXTENSION(YQCKit))
- (UIWebView * _Nonnull)frame:(CGFloat)x :(CGFloat)y :(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)frame:(CGRect)frame SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)size:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)size:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)origin:(CGPoint)origin SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)origin:(CGFloat)x :(CGFloat)y SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)center:(CGPoint)center SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)center:(CGFloat)centerX :(CGFloat)centerY SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)superView:(UIView * _Nonnull)superView SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)isHidden:(BOOL)isHidden SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)isUserInteractionEnabled:(BOOL)isUserInteractionEnabled SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)tag:(NSInteger)tag SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)shadowOpacity:(float)shadowOpacity SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)masksToBounds:(BOOL)masksToBounds SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)clipsToBounds:(BOOL)clipsToBounds SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)shadowColor:(UIColor * _Nonnull)shadowColor SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)shadowOffsetHeight:(CGFloat)shadowOffsetHeight SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)shadowOffsetWidth:(CGFloat)shadowOffsetWidth SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)shadowOffset:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)shadowOffset:(CGSize)shadowOffset SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)borderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)borderWidth:(CGFloat)borderWidth SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)cornerRadius:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)cornerRadiusWithClip:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)backgroundColor:(UIColor * _Nonnull)bgColor SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)alpha:(CGFloat)alpha SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)badgeText:(NSString * _Nonnull)badgeText SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)badgeDotWidth:(CGFloat)badgeDotWidth SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)badgeBgColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)badgeTextColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)badgeFont:(UIFont * _Nonnull)badgeFont SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)badgeHMargin:(CGFloat)badgeHMargin SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)badgeAlignRight:(BOOL)badgeAlignRight SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)badgeTop:(CGFloat)badgeTop SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)badgePadding:(CGFloat)hPadding :(CGFloat)vPadding SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)badgeBorderWidth:(CGFloat)badgeBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)badgeBorderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)showAllNumber:(BOOL)showAllNumber SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)translatesAutoresizingMaskIntoConstraints:(BOOL)translatesAutoresizingMaskIntoConstraints SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)tintColor:(UIColor * _Nonnull)tintColor SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)tintAdjustmentMode:(UIViewTintAdjustmentMode)tintAdjustmentMode SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)clearsContextBeforeDrawing:(BOOL)clearsContextBeforeDrawing SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)mask:(UIView * _Nullable)mask SWIFT_WARN_UNUSED_RESULT;
- (UIWebView * _Nonnull)isOpaque:(BOOL)isOpaque SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) void (^ _Nullable webViewAction)(UIWebView * _Nonnull);
- (UIWebView * _Nonnull)addAction:(void (^ _Nullable)(UIWebView * _Nonnull))action SWIFT_WARN_UNUSED_RESULT;
- (void)addTap:(void (^ _Nullable)(UIWebView * _Nonnull))action;
- (void)tapActionWithTap:(UITapGestureRecognizer * _Nonnull)tap;
- (UIWebView * _Nonnull)removeAction SWIFT_WARN_UNUSED_RESULT;
- (void)removeTap;
@end


@interface WKWebView (SWIFT_EXTENSION(YQCKit))
- (WKWebView * _Nonnull)frame:(CGFloat)x :(CGFloat)y :(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)frame:(CGRect)frame SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)size:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)size:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)origin:(CGPoint)origin SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)origin:(CGFloat)x :(CGFloat)y SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)center:(CGPoint)center SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)center:(CGFloat)centerX :(CGFloat)centerY SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)superView:(UIView * _Nonnull)superView SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)isHidden:(BOOL)isHidden SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)isUserInteractionEnabled:(BOOL)isUserInteractionEnabled SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)tag:(NSInteger)tag SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)shadowOpacity:(float)shadowOpacity SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)masksToBounds:(BOOL)masksToBounds SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)clipsToBounds:(BOOL)clipsToBounds SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)shadowColor:(UIColor * _Nonnull)shadowColor SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)shadowOffsetHeight:(CGFloat)shadowOffsetHeight SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)shadowOffsetWidth:(CGFloat)shadowOffsetWidth SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)shadowOffset:(CGFloat)width :(CGFloat)height SWIFT_WARN_UNUSED_RESULT;
- (UICollectionView * _Nonnull)shadowOffset:(CGSize)shadowOffset SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)borderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)borderWidth:(CGFloat)borderWidth SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)cornerRadius:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)cornerRadiusWithClip:(CGFloat)cornerRadius SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)backgroundColor:(UIColor * _Nonnull)bgColor SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)alpha:(CGFloat)alpha SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)tintColor:(UIColor * _Nonnull)tintColor SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)tintAdjustmentMode:(UIViewTintAdjustmentMode)tintAdjustmentMode SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)clearsContextBeforeDrawing:(BOOL)clearsContextBeforeDrawing SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)mask:(UIView * _Nullable)mask SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)isOpaque:(BOOL)isOpaque SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)translatesAutoresizingMaskIntoConstraints:(BOOL)translatesAutoresizingMaskIntoConstraints SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)badgeText:(NSString * _Nonnull)badgeText SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)badgeDotWidth:(CGFloat)badgeDotWidth SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)badgeBgColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)badgeTextColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)badgeFont:(UIFont * _Nonnull)badgeFont SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)badgeHMargin:(CGFloat)badgeHMargin SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)badgeAlignRight:(BOOL)badgeAlignRight SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)badgeTop:(CGFloat)badgeTop SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)badgePadding:(CGFloat)hPadding :(CGFloat)vPadding SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)badgeBorderWidth:(CGFloat)badgeBorderWidth SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)badgeBorderColor:(UIColor * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
- (WKWebView * _Nonnull)showAllNumber:(BOOL)showAllNumber SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) void (^ _Nullable wkWebViewAction)(WKWebView * _Nonnull);
- (WKWebView * _Nonnull)addAction:(void (^ _Nullable)(WKWebView * _Nonnull))action SWIFT_WARN_UNUSED_RESULT;
- (void)addTap:(void (^ _Nullable)(WKWebView * _Nonnull))action;
- (void)tapActionWithTap:(UITapGestureRecognizer * _Nonnull)tap;
- (WKWebView * _Nonnull)removeAction SWIFT_WARN_UNUSED_RESULT;
- (void)removeTap;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
